bin/ConsensusDriver.class bin/ClientDriver.class:
	mkdir -p bin
	javac -cp lib/json-simple-1.1.1.jar -d bin/ src/util/*.java src/util/network/*.java src/server/*.java src/framework/*.java src/tests/basicgame/*.java src/tests/uno/*.java

clean:
	cd bin; rm -rf *